app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('/admin', function (){
    return view('admin.index');
});

Route::group(['middleware'  => 'admin'], function() {
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/categories', 'AdminCategoriesController');
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id', 'is_active', 'photo_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role() {
        return $this->belongsTo('App\Role');
    }

    public function photo() {
        return $this->belongsTo('App\Photo');
    }

    public function posts() {
        return $this->hasMany('App\Post');
    }

    public function isAdmin() {
        if( $this->role->id === 1 && $this->is_active == 1 ) {
            return true;
        } else {
            return false;
        }
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts/admin')

@section('content')
    <h1>Create Users</h1>
    @include( 'includes/form_error')
    {!! Form::open([
            'method'	=> 'POST',
            'action'	=> 'AdminUsersController@store',
            'files'     => true,
        ]) !!}

        <div class="form-group">
            {!! Form::label('name', 'Name:') !!}
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
        </div>
        <br>
        <div class="form-group">
            {!! Form::label('email', 'Email:') !!}
            {!! Form::email('email', null, ['class' => 'form-control']) !!}
        </div>
        <br>
        <div class="form-group">
            {!! Form::label('role_id', 'Role:') !!}
            {!! Form::select('role_id', array('' => 'Choose Role...') + $roles, null, ['class' => 'form-control']) !!}
        </div>
        <br>
        <div class="form-group">
            {!! Form::label('is_active', 'Status:') !!}
            {!! Form::select('is_active', array(0 => 'Not Active', 1 => 'Active'), 0, ['class' => 'form-control']) !!}
        </div>
        <br>
        <div class="form-group">
            {!! Form::label('photo_id', 'User Picture:') !!}
            {!! Form::file('photo_id', null, ['class' => 'form-control']) !!}
        </div>
        <br>
        <div class="form-group">
            {!! Form::label('password', 'Password:') !!}
            {!! Form::password('password', ['class' => 'form-control']) !!}
        </div>
        <br>

        {!! Form::submit('Add User', ['class' => 'btn btn-primary']) !!}

    {!! Form::close() !!}
@stop

resources/views/admin/users/edit.blade.php
@extends('layouts/admin')

@section('content')
    <h1>Edit User</h1>
    <div class="row">
        @include( 'includes/form_error')
    </div>

    <div class="row">
        <div class="col-sm-3">
            <img src="{{$user->photo ? $user->photo->file : 'http://placehold.it/400x400'}}" class="img-responsive img-rounded">
        </div>
        <div class="col-sm-9">
            {!! Form::model(
                $user,
                [
                    'method'	=> 'PATCH',
                    'action'	=> array('AdminUsersController@update', $user->id),
                    'files'     => true,
                ]) !!}

            <div class="form-group">
                {!! Form::label('name', 'Name:') !!}
                {!! Form::text('name', null, ['class' => 'form-control']) !!}
            </div>
            <br>
            <div class="form-group">
                {!! Form::label('email', 'Email:') !!}
                {!! Form::email('email', null, ['class' => 'form-control']) !!}
            </div>
            <br>
            <div class="form-group">
                {!! Form::label('role_id', 'Role:') !!}
                {!! Form::select('role_id', $roles, null, ['class' => 'form-control']) !!}
            </div>
            <br>
            <div class="form-group">
                {!! Form::label('is_active', 'Status:') !!}
                {!! Form::select('is_active', array(0 => 'Not Active', 1 => 'Active'), null, ['class' => 'form-control']) !!}
            </div>
            <br>
            <div class="form-group">
                {!! Form::label('photo_id', 'User Picture:') !!}
                {!! Form::file('photo_id', null, ['class' => 'form-control']) !!}
            </div>
            <br>
            <div class="form-group">
                {!! Form::label('password', 'Password:') !!}
                {!! Form::password('password', ['class' => 'form-control']) !!}
            </div>
            <br>

            <div class="row">
                <div class="col-sm-1">
                    {!! Form::submit('Update User', ['class' => 'btn btn-primary']) !!}

                    {!! Form::close() !!}
                </div>

                <div class="col-sm-1"></div>
                <div class="col-sm-1">

                    {!! Form::open([
                        'method'	=> 'DELETE',
                        'action'	=> ['AdminUsersController@destroy', $user->id],
                    ]) !!}



                    {!! Form::submit('Delete User', ['class' => 'btn btn-danger']) !!}

                    {!! Form::close() !!}
                </div>
                <div class="col-sm-9"></div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/users/index.blade.php
@extends('layouts/admin')

@section('content')

    @if( session('user_deleted') )
        <p class="bg-danger">{{session('user_deleted')}}</p>
    @endif

    <h1>Users</h1>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>Photo</th>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Status</th>
            <th>Created</th>
            <th>Updated</th>
        </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
                <tr>
                    <td>{{$user->id}}</td>
                    <td><img height="50" src="{{$user->photo ? $user->photo->file : 'http://placehold.it/50x50'}}"></td>
                    <td><a href="{{route('admin.users.edit', $user->id)}}">{{$user->name}}</a></td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->role->name}}</td>
                    <td>{{$user->is_active == 1 ? 'Active' : 'Not Active'}}</td>
                    <td>{{$user->created_at->diffForHumans()}}</td>
                    <td>{{$user->updated_at->diffForHumans()}}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
@stop