app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('/admin', function (){
    return view('admin.index');
});

Route::group(['middleware'  => 'admin'], function() {
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/categories', 'AdminCategoriesController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = array(
        'user_id',
        'category_id',
        'photo_id',
        'title',
        'body'
    );

    public function user() {
        return $this->belongsTo('App\User');
    }

    public function category() {
        return $this->belongsTo('App\Category');
    }

    public function photo() {
        return $this->belongsTo('App\Photo');
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin')

@section('content')
    <h1>Create Post</h1>

    @include( 'includes/form_error')
    {!! Form::open([
            'method'	=> 'POST',
            'action'	=> 'AdminPostsController@store',
            'files'     => true,
        ]) !!}

    <div class="form-group">
        {!! Form::label('title', 'Title:') !!}
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
    </div>
    <br>
    <div class="form-group">
        {!! Form::label('category_id', 'Category:') !!}
        {!! Form::select('category_id', array('' => 'Choose Category...') + $categories, null, ['class' => 'form-control']) !!}
    </div>
    <br>
    <div class="form-group">
        {!! Form::label('photo_id', 'Post Thumbnail:') !!}
        {!! Form::file('photo_id', null, ['class' => 'form-control']) !!}
    </div>
    <br>
    <div class="form-group">
        {!! Form::label('body', 'Description:') !!}
        {!! Form::textarea('body', null, ['class' => 'form-control']) !!}
    </div>
    <br>

    {!! Form::submit('Add Post', ['class' => 'btn btn-primary']) !!}

    {!! Form::close() !!}
@stop

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin')

@section('content')
    <h1>Edit Post</h1>

    @include( 'includes/form_error')
    {!! Form::model(
            $post,
            [
                'method'	=> 'PATCH',
                'action'	=> array('AdminPostsController@update', $post->id),
                'files'     => true,
            ])
    !!}

    <div class="form-group">
        {!! Form::label('title', 'Title:') !!}
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
    </div>
    <br>
    <div class="form-group">
        {!! Form::label('category_id', 'Category:') !!}
        {!! Form::select('category_id', array('' => 'Choose Category...') + $categories, null, ['class' => 'form-control']) !!}
    </div>
    <br>
    <div class="form-group">
        {!! Form::label('photo_id', 'Post Thumbnail:') !!}
        {!! Form::file('photo_id', null, ['class' => 'form-control']) !!}
    </div>
    <br>
    <div class="form-group">
        {!! Form::label('body', 'Description:') !!}
        {!! Form::textarea('body', null, ['class' => 'form-control']) !!}
    </div>
    <br>

    <div class="row">
        <div class="col-sm-1">
            {!! Form::submit('Update', ['class' => 'btn btn-primary']) !!}
        </div>
        <div class="col-sm-1">
            {!! Form::open([
                'method'	=> 'DELETE',
                'action'	=> ['AdminPostsController@destroy', $post->id],
            ]) !!}

            {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}

            {!! Form::close() !!}
        </div>
        <div class="col-sm-10"></div>
    </div>


    {!! Form::close() !!}
@stop

resources/views/admin/posts/index.blade.php
@extends('layouts.admin')

@section('content')
    @if( session('post_deleted') )
        <p class="bg-danger">{{session('post_deleted')}}</p>
    @endif
    <h1>Posts</h1>

    <table class="table table-striped">
        <thead>
        <tr>
            <th>Id</th>
            <th>Photo</th>
            <th>Owner</th>
            <th>Category</th>
            <th>Title</th>
            <th>Body</th>
            <th>Created</th>
            <th>Updated</th>
        </tr>
        </thead>
        <tbody>
        @foreach($posts as $post)

            <tr>
                <td>{{$post->id}}</td>
                <td><img height="50" src="{{$post->photo ? $post->photo->file : 'http://placehold.it/50x50'}}"></td>
                <td>{{$post->user->name}}</td>
                <td>{{$post->category ? $post->category->name : 'Uncategorized'}}</td>
                <td><a href="{{route('admin.posts.edit', $post->id)}}">{{$post->title}}</a></td>
                <td>{{str_limit($post->body, 30)}}</td>
                <td>{{$post->created_at->diffForHumans()}}</td>
                <td>{{$post->updated_at->diffForHumans()}}</td>
            </tr>

        @endforeach
        </tbody>
    </table>
@stop