app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('/admin', function (){
    return view('admin.index');
});

Route::group(['middleware'  => 'admin'], function() {
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/categories', 'AdminCategoriesController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = array(
        'name'
    );
}

resources/views/admin/categories/edit.blade.php
@extends('layouts/admin')

@section('content')

    <h1>Category Edit</h1>

    <div class="col-sm-6">
        {!! Form::model(
                $category,
                [
                    'method'	=> 'PATCH',
                    'action'	=> array('AdminCategoriesController@update', $category->id),
                ]) !!}

        <div class="form-group">
            {!! Form::label('name', 'Name:') !!}
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
        </div>
        <br>

        <div class="row">
            <div class="col-sm-1">
                {!! Form::submit('Update', ['class' => 'btn btn-primary']) !!}

                {!! Form::close() !!}
            </div>

            <div class="col-sm-1"></div>
            <div class="col-sm-1">

                {!! Form::open([
                    'method'	=> 'DELETE',
                    'action'	=> ['AdminCategoriesController@destroy', $category->id],
                ]) !!}



                {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}

                {!! Form::close() !!}
            </div>
            <div class="col-sm-9"></div>
        </div>
    </div>
    <div class="col-sm-6">

    </div>
@stop

resources/views/admin/categories/index.blade.php
@extends('layouts/admin')

@section('content')

    @if( session('category_deleted') )
        <p class="bg-danger">{{session('category_deleted')}}</p>
    @endif

    <h1>Categories</h1>

    <div class="col-sm-6">
        {!! Form::open([
            'method'	=> 'POST',
            'action'	=> 'AdminCategoriesController@store',
        ]) !!}

        <div class="form-group">
            {!! Form::label('name', 'Name:') !!}
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
        </div>
        <br>
        {!! Form::submit('Add Category', ['class' => 'btn btn-primary']) !!}

        {!! Form::close() !!}
    </div>
    <div class="col-sm-6">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Created</th>
                <th>Updated</th>
            </tr>
            </thead>
            <tbody>
            @foreach($categories as $category)
                <tr>
                    <td>{{$category->id}}</td>
                    <td><a href="{{route('admin.categories.edit', $category->id)}}">{{$category->name}}</a></td>
                    <td>{{$category->created_at->diffForHumans()}}</td>
                    <td>{{$category->updated_at->diffForHumans()}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@stop